name: zelda-classic # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '2.50.2' # just for humans, typically '1.2+git' or '1.3.2'
summary: Remake of the classic Nintendo game
description: |
  From the authors: Zelda Classic is a tribute to (what we think is) the greatest video game of all time: Nintendo’s The Legend of Zelda. It has been developed into an exact replica of the NES version that we all know and love. Beyond that, Zelda Classic allows the development of new quests that can use either the traditional graphics or enhanced graphics, as well as new enemies, items, and challenges.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon:  zelda-classic_icon.png
title: Zelda Classic

apps:
  zelda-classic:
    command: zelda-l
parts:
  zelda-classic:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
#    build-packages: [default-jre]
#    stage-packages: [default-jre]
    organize:
      zelda-classic: build/
      zelda-classic.1: man/man1/

architectures:
  - build-on: amd64

